# Run tests with Travis CI

language: python
dist: xenial

python:
  - '3.7.5'

before_install:
  - export DJANGO_SETTINGS_MODULE=backend.settings_test
  - export PIP_USE_MIRRORS=true
  - export PIPENV_VENV_IN_PROJECT=true

install:
  - pip install pipenv
  - pipenv sync

script:
  - pipenv run python manage.py test -v2

cache:
  directories:
    - '.venv'
